# Generated by Django 4.2.25 on 2025-11-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(default='user@gmail.com', max_length=30)),
                ('user_phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
